### ISSUE TITLE
money to account 

### ISSUE THREAD

**Issue by bajro17** [MathieuMailhos/GoBtcMiner#1]
When it transfer money to account  how to know how much is mined?
And why it show first Miner 0 available than change it to 1
![screenshot from 2017-09-20 02-37-30](https://user-images.githubusercontent.com/16452914/30621677-c6b112d8-9dac-11e7-829c-b3c392baa616.png)

**Comment by mmailhos** [comment]
Hello, apologize for the delay. This project is nothing more than a prototype of the mining process. For now, it is not able to communicate with the Bitcoin blockchain as it is lacking some features (ex: merkle tree check implementation).
